// Auth actions
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// Videos actions
export const VIDEOS_FAVORITES_ADD = 'VIDEOS_FAVORITES_ADD';
export const VIDEOS_FAVORITES_REMOVE = 'VIDEOS_FAVORITES_REMOVE';
export const VIDEOS_LIKED_ADD = 'VIDEOS_LIKED_ADD';
export const VIDEOS_LIKED_REMOVE = 'VIDEOS_LIKED_REMOVE';

export const VIDEOS_COLLECTION_ADD = 'VIDEOS_COLLECTION_ADD';
export const VIDEOS_COLLECTION_REMOVE = 'VIDEOS_COLLECTION_REMOVE';